---
particles:
  radius: 3 # Радиус окружности для эффектов. Если не нужны - поставить 0
  open: # Эффекты при открытии
    count: 15
    scatter: 0.15
  particle: flame # Временно не работает

messages:
  given: 'Тебе выдан сундук!'

delay: 1.5 # Сколько секунд показывать после открытия всех сундуков
...